name: My Daily Habit
favicon: null
layout_spectrum: 0.5871630371548235
typography_spectrum: 0.5996109682600945
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.11856582458131015
  lightness: 0.816030636196956
  saturation: 0.9594103978015482
  rhythmicContrast: 0.14090612274594605
purpose: []
